/*==============================================================================

Southclaw's Interactivity Framework (SIF) (Formerly: Adventure API)

	Version: 1.0.0


	SIF/Overview
	{
		SIF is a collection of high-level include scripts to make the
		development of interactive features easy for the developer while
		maintaining quality front-end gameplay for players.
	}


==============================================================================*/

// Dependencies

#include <streamer>
#include <YSI\y_hooks>
#include <YSI\y_timers>
#include <YSI\y_iterate>
/*#include <YSI\y_utils>
#include <YSI\y_va>
#include <YSI\y_timers>
#include <YSI\y_hooks>
#include <YSI\y_iterate>
#include <YSI\y_ini>
#include <YSI\y_dialog>*/
#include <md-sort>
// SIF

#include "SIF\Core.pwn"
#include "SIF\Button.pwn"
#include "SIF\Door.pwn"
#include "SIF\Item.pwn"
#include "SIF\Inventory.pwn"
#include "SIF\Container.pwn"
#include <SIF\Backpack.pwn>
#include <SIF\extensions\ItemArrayData>
#include <SIF\extensions\ItemList>
#include <SIF\extensions\InventoryDialog>
#include <SIF\extensions\InventoryKeys>
#include <SIF\extensions\ContainerDialog>
#include <SIF\extensions\Craft>

